// Generated by Haxe 3.4.4
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var Color = { __ename__ : true, __constructs__ : ["Red","Green","Blue","Black","White","Gray","LightBlue","Purple","Yellow","DarkGray"] };
Color.Red = ["Red",0];
Color.Red.toString = $estr;
Color.Red.__enum__ = Color;
Color.Green = ["Green",1];
Color.Green.toString = $estr;
Color.Green.__enum__ = Color;
Color.Blue = ["Blue",2];
Color.Blue.toString = $estr;
Color.Blue.__enum__ = Color;
Color.Black = ["Black",3];
Color.Black.toString = $estr;
Color.Black.__enum__ = Color;
Color.White = ["White",4];
Color.White.toString = $estr;
Color.White.__enum__ = Color;
Color.Gray = ["Gray",5];
Color.Gray.toString = $estr;
Color.Gray.__enum__ = Color;
Color.LightBlue = ["LightBlue",6];
Color.LightBlue.toString = $estr;
Color.LightBlue.__enum__ = Color;
Color.Purple = ["Purple",7];
Color.Purple.toString = $estr;
Color.Purple.__enum__ = Color;
Color.Yellow = ["Yellow",8];
Color.Yellow.toString = $estr;
Color.Yellow.__enum__ = Color;
Color.DarkGray = ["DarkGray",9];
Color.DarkGray.toString = $estr;
Color.DarkGray.__enum__ = Color;
var Drawer = function(stage) {
	this.stage = stage;
	this.wallGraphics = new PIXI.Graphics();
	stage.addChild(this.wallGraphics);
	this.bitmaps = [];
	var _g = 0;
	while(_g < 24) {
		var i = _g++;
		this.bitmaps[i] = [];
		var _g1 = 0;
		while(_g1 < 50) {
			var j = _g1++;
			var bitmap = new PIXI.extras.BitmapText("",{ font : "font", tint : 16777215});
			this.bitmaps[i][j] = bitmap;
			bitmap.position.set(j * 15,i * 25 - 5);
			stage.addChild(bitmap);
		}
	}
};
Drawer.__name__ = true;
Drawer.colorToInt = function(color) {
	switch(color[1]) {
	case 0:
		return 16711680;
	case 1:
		return 65280;
	case 2:
		return 255;
	case 3:
		return 0;
	case 4:
		return 16777215;
	case 5:
		return 8421504;
	case 6:
		return 4376052;
	case 7:
		return 9060294;
	case 8:
		return 16776960;
	case 9:
		return 4210752;
	}
};
Drawer.prototype = {
	clear: function() {
		this.clearLines(0,24);
		this.wallGraphics.clear();
	}
	,clearLines: function(start,amount) {
		var _g1 = start;
		var _g = start + amount;
		while(_g1 < _g) {
			var i = _g1++;
			var _g2 = 0;
			while(_g2 < 50) {
				var j = _g2++;
				this.bitmaps[i][j].text = "";
			}
		}
	}
	,setMouseHelp: function(text) {
		this.clearLines(22,2);
		var yy = 22;
		if(this.getAmountOfLines(0,22,"Examine: " + text) == 1) {
			++yy;
		}
		var col = 0;
		if(text != "") {
			col = Drawer.colorToInt(Color.DarkGray);
		}
		var _g1 = 0;
		var _g = "Examine:".length;
		while(_g1 < _g) {
			var i = _g1++;
			this.setBackground(i,yy,col);
		}
		if(text != "") {
			this.drawText(0,yy,"Examine: " + text);
		}
	}
	,setWorldView: function(screenX,screenY,worldX,worldY,width,height) {
		this.screenX = screenX;
		this.screenY = screenY;
		this.worldX = worldX;
		this.worldY = worldY;
		this.worldWidth = width;
		this.worldHeight = height;
	}
	,setWorldCharacter: function(x,y,character,color) {
		if(color == null) {
			color = 16777215;
		}
		if(x >= this.worldX && y >= this.worldY && x < this.worldX + this.worldWidth && y < this.worldY + this.worldHeight) {
			this.setCharacter(x - this.worldX + this.screenX,y - this.worldY + this.screenY,character,color);
		}
	}
	,setWorldWall: function(x,y,color) {
		if(color == null) {
			color = 16777215;
		}
		if(x >= this.worldX && y >= this.worldY && x < this.worldX + this.worldWidth && y < this.worldY + this.worldHeight) {
			this.setBackground(x - this.worldX + this.screenX,y - this.worldY + this.screenY,color);
		}
	}
	,setCharacter: function(x,y,character,color) {
		if(color == null) {
			color = 16777215;
		}
		if(x < 0 || y < 0 || x >= 50 || y >= 24) {
			return;
		}
		this.bitmaps[y][x].text = character;
		this.bitmaps[y][x].tint = color;
	}
	,setBackground: function(x,y,color) {
		if(color == null) {
			color = 16777215;
		}
		if(x < 0 || y < 0 || x >= 50 || y >= 24) {
			return;
		}
		this.wallGraphics.beginFill(color);
		this.wallGraphics.drawRect(x * 15,y * 25,15,25);
		this.wallGraphics.endFill();
	}
	,drawText: function(x,y,text,color,wrap,maxWidth,getMaxX) {
		if(maxWidth == null) {
			maxWidth = -1;
		}
		if(wrap == null) {
			wrap = true;
		}
		if(color == null) {
			color = 16777215;
		}
		var lines = this.splitIntoLines(x,y,text,wrap,maxWidth,getMaxX);
		var minX = x;
		var _g = 0;
		while(_g < lines.length) {
			var line = lines[_g];
			++_g;
			var _g2 = 0;
			var _g1 = line.length;
			while(_g2 < _g1) {
				var i = _g2++;
				this.setCharacter(x,y,line.charAt(i),color);
				++x;
			}
			++y;
			x = minX;
		}
		return lines.length;
	}
	,splitIntoLines: function(x,y,text,wrap,maxWidth,getMaxX) {
		if(maxWidth == null) {
			maxWidth = -1;
		}
		if(wrap == null) {
			wrap = true;
		}
		var minX = x;
		var maxX;
		if(maxWidth == -1) {
			maxX = 50;
		} else {
			var val2 = x + maxWidth;
			if(val2 < 50) {
				maxX = val2;
			} else {
				maxX = 50;
			}
		}
		if(getMaxX == null) {
			getMaxX = function(i,j) {
				return i;
			};
		}
		var lines = text.split("\n");
		var finalLines = [];
		var finalLine = "";
		var _g = 0;
		while(_g < lines.length) {
			var line = lines[_g];
			++_g;
			var words = line.split(" ");
			var _g1 = 0;
			while(_g1 < words.length) {
				var word = words[_g1];
				++_g1;
				if(x + word.length >= getMaxX(maxX,finalLines.length)) {
					finalLines.push(finalLine);
					finalLine = "";
					x = minX;
					++y;
				}
				if(finalLine != "") {
					finalLine += " ";
				}
				finalLine += word;
				x += word.length + 1;
			}
			finalLines.push(finalLine);
			finalLine = "";
			++y;
			x = minX;
		}
		return finalLines;
	}
	,getAmountOfLines: function(x,y,text,wrap,maxWidth,getMaxX) {
		if(maxWidth == null) {
			maxWidth = -1;
		}
		if(wrap == null) {
			wrap = true;
		}
		return this.splitIntoLines(x,y,text,wrap,maxWidth,getMaxX).length;
	}
	,__class__: Drawer
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	split: function(s) {
		var d = "#__delim__#";
		return s.replace(this.r,d).split(d);
	}
	,__class__: EReg
};
var Focusable = function(keyboard,world,game) {
	this.keyboard = keyboard;
	this.world = world;
	this.game = game;
};
Focusable.__name__ = true;
Focusable.prototype = {
	get_showsWorld: function() {
		return false;
	}
	,update: function() {
	}
	,__class__: Focusable
};
var Game = function(application,stage,gameRect) {
	this.application = application;
	this.stage = stage;
	this.rect = gameRect;
	this.drawer = new Drawer(stage);
	this.keyboard = new Keyboard();
	this.world = new World(this.drawer);
	this.mouse = new Mouse(stage,this.world);
	this.info = new ui_InfoDisplay(this.keyboard,this.world,this);
	this.world.info = this.info;
	this.player = new Player(this.keyboard,this.world,this);
	this.world.player = this.player;
	this.focusedElement = this.player;
	this.drawer.clear();
	this.world.draw();
};
Game.__name__ = true;
Game.prototype = {
	update: function(timeMod) {
		this.keyboard.update();
		this.focusedElement.update();
		this.postUpdate();
	}
	,focus: function(element) {
		this.focusedElement = element;
	}
	,nextFocus: function() {
		this.focus(this.player);
	}
	,postUpdate: function() {
		this.keyboard.postUpdate();
		if(this.focusedElement.get_showsWorld()) {
			var mouseWorldPos = this.world.toWorldPoint(this.mouse.mousePosition);
			if(mouseWorldPos != null) {
				this.drawer.setMouseHelp(this.world.getQuickExamine(mouseWorldPos));
			} else {
				this.drawer.setMouseHelp("");
			}
		}
	}
	,beforeStep: function() {
		this.drawer.clear();
		this.info.clear();
	}
	,afterStep: function() {
		this.world.update();
		this.info.processInfo(this.drawer);
	}
	,__class__: Game
};
var GameLoader = function(then) {
	this.loader = new PIXI.loaders.Loader();
	this.loader.add("fonts/font-export.fnt");
	this.loader["use"](function(res,next) {
		next();
	});
	this.loader.load(then);
};
GameLoader.__name__ = true;
GameLoader.prototype = {
	update: function() {
		console.log(this.loader.progress + "% loaded");
	}
	,__class__: GameLoader
};
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
var Keyboard = function() {
	var _gthis = this;
	var _g = [];
	var _g1 = 0;
	while(_g1 < 256) {
		var i = _g1++;
		_g.push(false);
	}
	this.pressed = _g;
	var _g11 = [];
	var _g2 = 0;
	while(_g2 < 256) {
		var i1 = _g2++;
		_g11.push(false);
	}
	this.down = _g11;
	window.addEventListener("keydown",function(event) {
		var keyCode = event.keyCode;
		if(keyCode < 256) {
			_gthis.pressed[keyCode] = true;
			_gthis.down[keyCode] = true;
		}
	},false);
	window.addEventListener("keyup",function(event1) {
		var keyCode1 = event1.keyCode;
		if(keyCode1 < 256) {
			_gthis.down[keyCode1] = false;
		}
	},false);
};
Keyboard.__name__ = true;
Keyboard.getLetterCode = function(letter) {
	var code = HxOverrides.cca(letter,0);
	if(code >= 97 && code <= 122) {
		code -= 32;
	}
	return code;
};
Keyboard.prototype = {
	anyConfirm: function() {
		if(!this.down[32]) {
			return this.down[13];
		} else {
			return true;
		}
	}
	,update: function() {
	}
	,postUpdate: function() {
		var _g = 0;
		while(_g < 256) {
			var i = _g++;
			this.pressed[i] = false;
		}
	}
	,__class__: Keyboard
};
var pixi_plugins_app_Application = function() {
	this._animationFrameId = null;
	this.pixelRatio = 1;
	this.autoResize = true;
	this.transparent = false;
	this.antialias = false;
	this.forceFXAA = false;
	this.roundPixels = false;
	this.legacy = false;
	this.clearBeforeRender = true;
	this.preserveDrawingBuffer = false;
	this.backgroundColor = 16777215;
	this.width = window.innerWidth;
	this.height = window.innerHeight;
	this.position = "static";
};
pixi_plugins_app_Application.__name__ = true;
pixi_plugins_app_Application.prototype = {
	start: function(rendererType,parentDom,canvasElement) {
		if(rendererType == null) {
			rendererType = "auto";
		}
		if(canvasElement == null) {
			this.canvas = window.document.createElement("canvas");
			this.canvas.style.width = this.width + "px";
			this.canvas.style.height = this.height + "px";
			this.canvas.style.position = this.position;
		} else {
			this.canvas = canvasElement;
		}
		if(this.autoResize) {
			window.onresize = $bind(this,this._onWindowResize);
		}
		var renderingOptions = { };
		renderingOptions.width = this.width | 0;
		renderingOptions.height = this.height | 0;
		renderingOptions.view = this.canvas;
		renderingOptions.backgroundColor = this.backgroundColor;
		renderingOptions.resolution = this.pixelRatio;
		renderingOptions.antialias = this.antialias;
		renderingOptions.forceFXAA = this.forceFXAA;
		renderingOptions.autoResize = this.autoResize;
		renderingOptions.transparent = this.transparent;
		renderingOptions.clearBeforeRender = this.clearBeforeRender;
		renderingOptions.preserveDrawingBuffer = this.preserveDrawingBuffer;
		renderingOptions.roundPixels = this.roundPixels;
		renderingOptions.legacy = this.legacy;
		if(rendererType == null) {
			this.app = new PIXI.Application(renderingOptions);
		} else if(rendererType == "canvas") {
			renderingOptions.forceCanvas = true;
			this.app = new PIXI.Application(renderingOptions);
		} else {
			this.app = new PIXI.Application(renderingOptions);
		}
		this.stage = this.app.stage;
		this.renderer = this.app.renderer;
		if(parentDom == null) {
			window.document.body.appendChild(this.app.view);
		} else {
			parentDom.appendChild(this.app.view);
		}
		this.app.ticker.add($bind(this,this._onRequestAnimationFrame));
	}
	,_onWindowResize: function(event) {
		this.width = window.innerWidth;
		this.height = window.innerHeight;
		this.app.renderer.resize(this.width,this.height);
		this.canvas.style.width = this.width + "px";
		this.canvas.style.height = this.height + "px";
		if(this.onResize != null) {
			this.onResize();
		}
	}
	,_onRequestAnimationFrame: function() {
		if(this.onUpdate != null) {
			this.onUpdate(this.app.ticker.deltaTime);
		}
	}
	,__class__: pixi_plugins_app_Application
};
var Main = function() {
	pixi_plugins_app_Application.call(this);
	this.init();
};
Main.__name__ = true;
Main.main = function() {
	new Main();
};
Main.__super__ = pixi_plugins_app_Application;
Main.prototype = $extend(pixi_plugins_app_Application.prototype,{
	init: function() {
		var _gthis = this;
		this.autoResize = false;
		this.onUpdate = $bind(this,this.update);
		this.backgroundColor = 0;
		this.clearBeforeRender = true;
		this.width = 750;
		this.height = 600;
		this.initConfig();
		pixi_plugins_app_Application.prototype.start.call(this);
		this.gameRect = new common_Rectangle(0,0,750,600);
		this.loader = new GameLoader(function() {
			console.log("loaded");
			_gthis.loader = null;
			_gthis.game = new Game(_gthis,_gthis.stage,_gthis.gameRect);
		});
		this.canvas.addEventListener("contextmenu",function(ev) {
			ev.preventDefault();
			return false;
		});
	}
	,initConfig: function() {
		try {
			var params = haxe_web_Request.getParams();
		} catch( e ) {
		}
	}
	,update: function(elapsedTime) {
		if(this.game != null) {
			this.game.update(elapsedTime);
		} else if(this.loader != null) {
			this.loader.update();
		}
	}
	,__class__: Main
});
Math.__name__ = true;
var Mouse = function(stage,world) {
	this.mousePosition = new common_Point(-1,-1);
	this.mouseRawPosition = new common_Point(-1,-1);
	var _gthis = this;
	stage.interactive = true;
	stage.on("pointermove",function(e) {
		var point = e.data.getLocalPosition(stage);
		var tmp = new common_Point(Math.floor(point.x),Math.floor(point.y));
		_gthis.mouseRawPosition = tmp;
		_gthis.mousePosition = new common_Point(_gthis.mouseRawPosition.x / 15 | 0,_gthis.mouseRawPosition.y / 25 | 0);
	});
};
Mouse.__name__ = true;
Mouse.prototype = {
	__class__: Mouse
};
var Player = function(keyboard,world,game) {
	Focusable.call(this,keyboard,world,game);
	this.ownBody = new worldElements_creatures_Human(world,new common_Point(1,1));
	world.addElement(this.ownBody);
	this.controllingBody = this.ownBody;
};
Player.__name__ = true;
Player.__super__ = Focusable;
Player.prototype = $extend(Focusable.prototype,{
	get_showsWorld: function() {
		return true;
	}
	,update: function() {
		var xMove = 0;
		var yMove = 0;
		if(this.keyboard.pressed[37] || this.keyboard.pressed[Keyboard.getLetterCode("A")]) {
			--xMove;
		}
		if(this.keyboard.pressed[39] || this.keyboard.pressed[Keyboard.getLetterCode("D")]) {
			++xMove;
		}
		if(this.keyboard.pressed[38] || this.keyboard.pressed[Keyboard.getLetterCode("W")]) {
			--yMove;
		}
		if(this.keyboard.pressed[40] || this.keyboard.pressed[Keyboard.getLetterCode("S")]) {
			++yMove;
		}
		var moveDirection = null;
		if(xMove == -1) {
			moveDirection = common_Direction.Left;
		} else if(xMove == 1) {
			moveDirection = common_Direction.Right;
		} else if(yMove == -1) {
			moveDirection = common_Direction.Up;
		} else if(yMove == 1) {
			moveDirection = common_Direction.Down;
		}
		if(moveDirection != null) {
			if(this.controllingBody.movement.canMove(this.world,this.controllingBody,moveDirection)) {
				this.game.beforeStep();
				this.controllingBody.movement.moveInDirection(this.world,this.controllingBody,moveDirection);
				this.controllingBody.hasMoved = true;
				this.game.afterStep();
			}
		}
	}
	,__class__: Player
});
var World = function(drawer) {
	this.viewY = 0;
	this.viewX = 0;
	this.height = 20;
	this.width = 50;
	this.drawer = drawer;
	this.elements = [];
	var _g = [];
	var _g2 = 0;
	var _g1 = this.width;
	while(_g2 < _g1) {
		var i = _g2++;
		var _g3 = [];
		var _g5 = 0;
		var _g4 = this.height;
		while(_g5 < _g4) {
			var j = _g5++;
			_g3.push([]);
		}
		_g.push(_g3);
	}
	this.elementsByPosition = _g;
	this.elements.push(new worldElements_Wall(this,new common_Point(0,0)));
	this.elements.push(new worldElements_Wall(this,new common_Point(1,0)));
	this.elements.push(new worldElements_Wall(this,new common_Point(2,0)));
	this.elements.push(new worldElements_Wall(this,new common_Point(3,0)));
	this.elements.push(new worldElements_creatures_Rat(this,new common_Point(5,2)));
};
World.__name__ = true;
World.prototype = {
	addElement: function(element) {
		this.elements.push(element);
	}
	,addToElementsAtPosition: function(element,position) {
		this.elementsByPosition[position.x][position.y].push(element);
	}
	,removeFromElementsAtPosition: function(element,position) {
		HxOverrides.remove(this.elementsByPosition[position.x][position.y],element);
	}
	,update: function() {
		this.removeElementsWhereNeeded();
		var _g = 0;
		var _g1 = this.elements;
		while(_g < _g1.length) {
			var element = _g1[_g];
			++_g;
			element.update();
		}
		this.removeElementsWhereNeeded();
		this.draw();
	}
	,removeElementsWhereNeeded: function() {
		var i = this.elements.length - 1;
		while(i >= 0) {
			var element = this.elements[i];
			if(element.shouldRemove()) {
				this.removeFromElementsAtPosition(element,element.position);
				this.elements.splice(i,1);
			}
			--i;
		}
	}
	,draw: function() {
		this.drawer.setWorldView(0,2,this.viewX,this.viewY,50,20);
		var _g = 0;
		var _g1 = this.elements;
		while(_g < _g1.length) {
			var element = _g1[_g];
			++_g;
			element.draw(this.drawer);
		}
	}
	,positionInDirection: function(position,direction) {
		var newPosition = new common_Point(position.x,position.y);
		switch(direction[1]) {
		case 0:
			newPosition.x -= 1;
			break;
		case 1:
			newPosition.x += 1;
			break;
		case 2:
			newPosition.y -= 1;
			break;
		case 3:
			newPosition.y += 1;
			break;
		}
		if(this.isPositionInWorld(newPosition)) {
			return newPosition;
		} else {
			return null;
		}
	}
	,isPositionInWorld: function(position) {
		if(position.x >= 0 && position.y >= 0 && position.x < this.width) {
			return position.y < this.height;
		} else {
			return false;
		}
	}
	,elementsAtPosition: function(position) {
		return this.elementsByPosition[position.x][position.y];
	}
	,toWorldPoint: function(point) {
		var newPoint = new common_Point(point.x,point.y);
		newPoint.x -= this.viewX;
		newPoint.y -= 2 + this.viewY;
		if(this.isPositionInWorld(newPoint)) {
			return newPoint;
		} else {
			return null;
		}
	}
	,getQuickExamine: function(position) {
		var help = "";
		var _g = 0;
		var _g1 = this.elementsAtPosition(position);
		while(_g < _g1.length) {
			var element = _g1[_g];
			++_g;
			if(help != "") {
				help += "\n";
			}
			help += element.getInfo();
		}
		return help;
	}
	,__class__: World
};
var common_ArrayExtensions = function() { };
common_ArrayExtensions.__name__ = true;
common_ArrayExtensions.any = function(array,fn) {
	var _g = 0;
	while(_g < array.length) {
		var val = array[_g];
		++_g;
		if(fn(val)) {
			return true;
		}
	}
	return false;
};
var common_Rectangle = function(x,y,width,height) {
	this.x = x;
	this.y = y;
	this.width = width;
	this.height = height;
};
common_Rectangle.__name__ = true;
common_Rectangle.prototype = {
	__class__: common_Rectangle
};
var common_Point = function(x,y) {
	this.x = x;
	this.y = y;
};
common_Point.__name__ = true;
common_Point.prototype = {
	__class__: common_Point
};
var common_Direction = { __ename__ : true, __constructs__ : ["Left","Right","Up","Down"] };
common_Direction.Left = ["Left",0];
common_Direction.Left.toString = $estr;
common_Direction.Left.__enum__ = common_Direction;
common_Direction.Right = ["Right",1];
common_Direction.Right.toString = $estr;
common_Direction.Right.__enum__ = common_Direction;
common_Direction.Up = ["Up",2];
common_Direction.Up.toString = $estr;
common_Direction.Up.__enum__ = common_Direction;
common_Direction.Down = ["Down",3];
common_Direction.Down.toString = $estr;
common_Direction.Down.__enum__ = common_Direction;
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,__class__: haxe_ds_StringMap
};
var haxe_web_Request = function() { };
haxe_web_Request.__name__ = true;
haxe_web_Request.getParams = function() {
	var get = HxOverrides.substr(window.location.search,1,null);
	var params = new haxe_ds_StringMap();
	var _g = 0;
	var _g1 = new EReg("[&;]","g").split(get);
	while(_g < _g1.length) {
		var p = _g1[_g];
		++_g;
		var pl = p.split("=");
		if(pl.length < 2) {
			continue;
		}
		var name = pl.shift();
		var key = decodeURIComponent(name.split("+").join(" "));
		var s = pl.join("=");
		var value = decodeURIComponent(s.split("+").join(" "));
		if(__map_reserved[key] != null) {
			params.setReserved(key,value);
		} else {
			params.h[key] = value;
		}
	}
	return params;
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var ui_InfoDisplay = function(keyboard,world,game) {
	this.currentLine = 0;
	this.info = "";
	Focusable.call(this,keyboard,world,game);
};
ui_InfoDisplay.__name__ = true;
ui_InfoDisplay.__super__ = Focusable;
ui_InfoDisplay.prototype = $extend(Focusable.prototype,{
	get_showsWorld: function() {
		return true;
	}
	,clear: function() {
		this.info = "";
	}
	,addInfo: function(info) {
		if(this.info != "") {
			this.info += " ";
		}
		this.info += info;
	}
	,processInfo: function(drawer) {
		var addToLast = "...";
		var lines = drawer.splitIntoLines(0,0,this.info,null,null,function(orig,ln) {
			if(ln % 2 == 1) {
				return orig - addToLast.length;
			} else {
				return orig;
			}
		});
		if(lines.length > 2) {
			var _g1 = 0;
			var _g = lines.length - 1;
			while(_g1 < _g) {
				var i = _g1++;
				if(i % 2 == 1) {
					if(lines[i].charAt(lines[i].length - 1) != ".") {
						lines[i] += ".";
					}
					lines[i] += "..";
				}
			}
			this.game.focus(this);
		}
		this.currentLines = lines;
		this.currentLine = 0;
		this.drawCurrentLines(drawer);
	}
	,update: function() {
		if(this.keyboard.anyConfirm()) {
			this.currentLine += 2;
			this.drawCurrentLines(this.game.drawer);
			if(this.currentLine >= this.currentLines.length - 2) {
				this.game.nextFocus();
			}
		}
	}
	,drawCurrentLines: function(drawer) {
		drawer.clearLines(0,2);
		if(this.currentLines.length > this.currentLine) {
			drawer.drawText(0,0,this.currentLines[this.currentLine]);
		}
		if(this.currentLines.length > this.currentLine + 1) {
			drawer.drawText(0,1,this.currentLines[this.currentLine + 1]);
		}
	}
	,__class__: ui_InfoDisplay
});
var worldElements_WorldElement = function(world,position) {
	this.world = world;
	this.set_position(position);
	this.character = "";
	this.color = Drawer.colorToInt(Color.White);
	this.init();
};
worldElements_WorldElement.__name__ = true;
worldElements_WorldElement.prototype = {
	get_isBlocking: function() {
		return false;
	}
	,set_position: function(newPosition) {
		if(this.position != null) {
			this.world.removeFromElementsAtPosition(this,this.position);
		}
		this.position = newPosition;
		this.world.addToElementsAtPosition(this,newPosition);
		return this.position;
	}
	,init: function() {
	}
	,update: function() {
	}
	,draw: function(drawer) {
		drawer.setWorldCharacter(this.position.x,this.position.y,this.character,this.color);
	}
	,getInfo: function() {
		return "You don't know what this is!";
	}
	,hasActionFor: function(triggeringWorldElement) {
		return false;
	}
	,performActionFor: function(triggeringWorldElement) {
	}
	,shouldRemove: function() {
		return false;
	}
	,isInterestingForPlayer: function() {
		return false;
	}
	,__class__: worldElements_WorldElement
};
var worldElements_Wall = function(world,position) {
	worldElements_WorldElement.call(this,world,position);
};
worldElements_Wall.__name__ = true;
worldElements_Wall.__super__ = worldElements_WorldElement;
worldElements_Wall.prototype = $extend(worldElements_WorldElement.prototype,{
	get_isBlocking: function() {
		return true;
	}
	,draw: function(drawer) {
		drawer.setWorldWall(this.position.x,this.position.y,this.color);
	}
	,getInfo: function() {
		return "A wall.";
	}
	,__class__: worldElements_Wall
});
var worldElements_creatures_Creature = function(world,position) {
	this.creatureFullAttackVerb = "bite";
	this.creatureAttackVerb = "bit";
	this.creatureTypeAorAn = "a";
	this.creatureTypeName = "creature";
	this.hasMoved = false;
	worldElements_WorldElement.call(this,world,position);
};
worldElements_creatures_Creature.__name__ = true;
worldElements_creatures_Creature.__super__ = worldElements_WorldElement;
worldElements_creatures_Creature.prototype = $extend(worldElements_WorldElement.prototype,{
	get_isBlocking: function() {
		return true;
	}
	,init: function() {
		this.movement = new worldElements_creatures_movement_BasicMovement();
		this.stats = new worldElements_creatures_stats_CreatureStats(1,1);
		this.basicAttack = new worldElements_creatures_actions_DirectionalAttack(this);
	}
	,update: function() {
		worldElements_WorldElement.prototype.update.call(this);
		if(!this.hasMoved) {
			this.movement.move(this.world,this);
			this.hasMoved = true;
		}
	}
	,getInfo: function() {
		var pre = "";
		var post = "";
		if(this.world.player.ownBody == this && this.world.player.controllingBody == this) {
			pre = "You, ";
		} else if(this.world.player.controllingBody == this) {
			post = ", controlled by you";
		} else if(this.world.player.ownBody == this) {
			pre = "Your own body, ";
		}
		var str = pre + ("" + this.creatureTypeAorAn + " " + this.creatureTypeName + post + " - " + this.stats.getInfo());
		if(str.length == 0) {
			return str;
		} else {
			return str.charAt(0).toUpperCase() + HxOverrides.substr(str,1,null);
		}
	}
	,hasActionFor: function(triggeringWorldElement) {
		if(js_Boot.__instanceof(triggeringWorldElement,worldElements_creatures_Creature)) {
			return true;
		}
		return false;
	}
	,performActionFor: function(triggeringWorldElement) {
		if(js_Boot.__instanceof(triggeringWorldElement,worldElements_creatures_Creature)) {
			triggeringWorldElement.attack(this);
		}
	}
	,attack: function(what) {
		this.basicAttack.useOnElement(what);
	}
	,shouldRemove: function() {
		if(this.stats.hp <= 0) {
			var tmp = this.world.info;
			var str = "" + this.getNameToUse() + " has been defeated.";
			tmp.addInfo(str.length == 0 ? str : str.charAt(0).toUpperCase() + HxOverrides.substr(str,1,null));
			return true;
		}
		return false;
	}
	,isInterestingForPlayer: function() {
		if(this.world.player.ownBody != this) {
			return this.world.player.controllingBody == this;
		} else {
			return true;
		}
	}
	,getNameToUse: function() {
		if(this.world.player.ownBody == this || this.world.player.controllingBody == this) {
			return "you";
		} else {
			return "the " + this.creatureTypeName;
		}
	}
	,getReferenceToUse: function(itself) {
		if(itself == null) {
			itself = false;
		}
		if(this.world.player.ownBody == this || this.world.player.controllingBody == this) {
			if(itself) {
				return "yourself";
			} else {
				return "you";
			}
		} else if(itself) {
			return "itself";
		} else {
			return "it";
		}
	}
	,__class__: worldElements_creatures_Creature
});
var worldElements_creatures_Human = function(world,position) {
	worldElements_creatures_Creature.call(this,world,position);
};
worldElements_creatures_Human.__name__ = true;
worldElements_creatures_Human.__super__ = worldElements_creatures_Creature;
worldElements_creatures_Human.prototype = $extend(worldElements_creatures_Creature.prototype,{
	init: function() {
		worldElements_creatures_Creature.prototype.init.call(this);
		this.color = Drawer.colorToInt(Color.LightBlue);
		this.character = "@";
		this.creatureTypeName = "human";
		this.stats.setMaxHP(10);
		this.stats.setMaxAP(10);
		this.stats.setAttack(3);
		this.creatureAttackVerb = "hit";
		this.creatureFullAttackVerb = "hit";
	}
	,__class__: worldElements_creatures_Human
});
var worldElements_creatures_Rat = function(world,position) {
	worldElements_creatures_Creature.call(this,world,position);
};
worldElements_creatures_Rat.__name__ = true;
worldElements_creatures_Rat.__super__ = worldElements_creatures_Creature;
worldElements_creatures_Rat.prototype = $extend(worldElements_creatures_Creature.prototype,{
	init: function() {
		worldElements_creatures_Creature.prototype.init.call(this);
		this.color = 14259306;
		this.character = "r";
		this.creatureTypeName = "rat";
		this.stats.setMaxHP(5);
		this.stats.setMaxAP(1);
		this.stats.setAttack(1);
	}
	,__class__: worldElements_creatures_Rat
});
var worldElements_creatures_actions_AttackResult = { __ename__ : true, __constructs__ : ["Damage","Block"] };
worldElements_creatures_actions_AttackResult.Damage = function(damage) { var $x = ["Damage",0,damage]; $x.__enum__ = worldElements_creatures_actions_AttackResult; $x.toString = $estr; return $x; };
worldElements_creatures_actions_AttackResult.Block = ["Block",1];
worldElements_creatures_actions_AttackResult.Block.toString = $estr;
worldElements_creatures_actions_AttackResult.Block.__enum__ = worldElements_creatures_actions_AttackResult;
var worldElements_creatures_actions_AttackCalculator = function() { };
worldElements_creatures_actions_AttackCalculator.__name__ = true;
worldElements_creatures_actions_AttackCalculator.basicAttack = function(attackingCreature,attackedCreature) {
	var attackPart = attackingCreature.stats.attack;
	var defencePart = attackedCreature.stats.defence;
	var damage = attackPart - defencePart;
	attackedCreature.stats.hp -= damage;
	var result;
	if(damage > 0) {
		result = worldElements_creatures_actions_AttackResult.Damage(damage);
	} else if(defencePart > 0) {
		result = worldElements_creatures_actions_AttackResult.Block;
	} else {
		result = worldElements_creatures_actions_AttackResult.Damage(0);
	}
	return result;
};
var worldElements_creatures_actions_CreatureAction = function(creature) {
	this.creature = creature;
};
worldElements_creatures_actions_CreatureAction.__name__ = true;
worldElements_creatures_actions_CreatureAction.prototype = {
	__class__: worldElements_creatures_actions_CreatureAction
};
var worldElements_creatures_actions_DirectionAction = function(creature) {
	worldElements_creatures_actions_CreatureAction.call(this,creature);
};
worldElements_creatures_actions_DirectionAction.__name__ = true;
worldElements_creatures_actions_DirectionAction.__super__ = worldElements_creatures_actions_CreatureAction;
worldElements_creatures_actions_DirectionAction.prototype = $extend(worldElements_creatures_actions_CreatureAction.prototype,{
	__class__: worldElements_creatures_actions_DirectionAction
});
var worldElements_creatures_actions_DirectionalAttack = function(creature) {
	worldElements_creatures_actions_DirectionAction.call(this,creature);
};
worldElements_creatures_actions_DirectionalAttack.__name__ = true;
worldElements_creatures_actions_DirectionalAttack.__super__ = worldElements_creatures_actions_DirectionAction;
worldElements_creatures_actions_DirectionalAttack.prototype = $extend(worldElements_creatures_actions_DirectionAction.prototype,{
	useOnElement: function(elementHere) {
		var creatureHere = elementHere;
		var result = worldElements_creatures_actions_AttackCalculator.basicAttack(this.creature,creatureHere);
		if(this.creature.isInterestingForPlayer() || elementHere.isInterestingForPlayer()) {
			var text;
			switch(result[1]) {
			case 0:
				var damage = result[2];
				var str = "" + this.creature.getNameToUse() + " " + this.creature.creatureAttackVerb + " " + creatureHere.getNameToUse() + " for " + damage + " damage.";
				if(str.length == 0) {
					text = str;
				} else {
					text = str.charAt(0).toUpperCase() + HxOverrides.substr(str,1,null);
				}
				break;
			case 1:
				var str1 = "" + this.creature.getNameToUse() + " tried to " + this.creature.creatureFullAttackVerb + " " + creatureHere.getNameToUse() + ", but " + creatureHere.getReferenceToUse() + " defended " + creatureHere.getReferenceToUse(true) + ".";
				if(str1.length == 0) {
					text = str1;
				} else {
					text = str1.charAt(0).toUpperCase() + HxOverrides.substr(str1,1,null);
				}
				break;
			}
			this.creature.world.info.addInfo(text);
		}
	}
	,__class__: worldElements_creatures_actions_DirectionalAttack
});
var worldElements_creatures_movement_Movement = function() { };
worldElements_creatures_movement_Movement.__name__ = true;
worldElements_creatures_movement_Movement.prototype = {
	canMove: function(world,creature,direction) {
		var newPosition = world.positionInDirection(creature.position,direction);
		if(newPosition != null) {
			var elementsHere = world.elementsAtPosition(newPosition);
			if(!this.isBlockingElementIn(world,elementsHere)) {
				return true;
			}
			if(common_ArrayExtensions.any(elementsHere,function(e) {
				return e.hasActionFor(creature);
			})) {
				return true;
			}
		}
		return false;
	}
	,isBlockingElementIn: function(world,elementsHere) {
		if(!common_ArrayExtensions.any(elementsHere,function(e) {
			return e.get_isBlocking();
		})) {
			return false;
		}
		return true;
	}
	,move: function(world,creature) {
	}
	,moveInDirection: function(world,creature,direction) {
		var newPosition = world.positionInDirection(creature.position,direction);
		if(newPosition != null) {
			var elementsHere = world.elementsAtPosition(newPosition);
			if(!this.isBlockingElementIn(world,elementsHere)) {
				creature.set_position(newPosition);
			}
			var _g = 0;
			while(_g < elementsHere.length) {
				var elem = elementsHere[_g];
				++_g;
				if(elem != creature && elem.hasActionFor(creature)) {
					elem.performActionFor(creature);
					break;
				}
			}
		}
	}
	,__class__: worldElements_creatures_movement_Movement
};
var worldElements_creatures_movement_BasicMovement = function() {
};
worldElements_creatures_movement_BasicMovement.__name__ = true;
worldElements_creatures_movement_BasicMovement.__super__ = worldElements_creatures_movement_Movement;
worldElements_creatures_movement_BasicMovement.prototype = $extend(worldElements_creatures_movement_Movement.prototype,{
	__class__: worldElements_creatures_movement_BasicMovement
});
var worldElements_creatures_stats_CreatureStats = function(hp,ap,attack,defence) {
	if(defence == null) {
		defence = 0;
	}
	if(attack == null) {
		attack = 0;
	}
	this.maxHP = hp;
	this.maxAP = ap;
	this.attack = attack;
	this.defence = defence;
	this.hp = hp;
	this.ap = ap;
};
worldElements_creatures_stats_CreatureStats.__name__ = true;
worldElements_creatures_stats_CreatureStats.prototype = {
	getInfo: function() {
		return "HP: " + this.hp + "/" + this.maxHP + "; AP: " + this.ap + "/" + this.maxAP;
	}
	,setMaxHP: function(newMaxHP) {
		var diff = newMaxHP - this.maxHP;
		this.maxHP = newMaxHP;
		this.hp += diff;
	}
	,setMaxAP: function(newMaxAP) {
		var diff = newMaxAP - this.maxAP;
		this.maxAP = newMaxAP;
		this.ap += diff;
	}
	,setAttack: function(attack) {
		this.attack = attack;
	}
	,__class__: worldElements_creatures_stats_CreatureStats
};
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
var __map_reserved = {};
js_Boot.__toStr = ({ }).toString;
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=game_js.js.map